### ISSUE TITLE
win7下启动 weex dev 环境问题

### ISSUE THREAD

**Issue by weue** [icepy/weex-generator-package#1]
1.win7下启动 weex dev 环境后，cannot get
2.启动 vue web dev 环境后会删除div#root，浏览器报错[Vue warn]: Cannot find element: #root

**Comment by icepy** [comment]
@weue  

1. 访问的文件名，是你自己配置了，比如你配置`weex-home`，那么启动的服务器需要访问localhost:8089/weex-home-dev.js
2. web 你是使用`npm run dev:web`启动的？这个不会删除div#root，检查一下你自己的代码。
